batch_size: 32
checkpoint: src/ckps/scibert/scibert_full
checkpoint_dir: src/ckps/scibert
checkpoint_every: null
config_file: src/configs/scibert/scibert_full.yaml
dataset: abstrct
early_stopping:
  min_delta: 0.003
  patience: 4
experiment_name: scibert_full
ft_setting:
  type: full
learning_rate: 5.0e-05
log_every: 20
max_length: 128
model: scibert
num_epochs: 10
num_workers: 4
seed: 42
visualize: false
warmup: 0.05
weight_decay: 0.01
