accum_steps: 2
batch_size: 32
checkpoint: src/ckpts/sbert_full_mixed
checkpoint_dir: src/ckpts
checkpoint_every: null
class_weights:
- 1.0
- 1.0
- 1.0
config_file: src/configs/sbert_full_mixed.yaml
dataset: mixed
early_stopping:
  min_delta: 0.001
  patience: 7
experiment_name: sbert_full_mixed
ft_setting:
  ftname: full
  lr_backbone: 5.0e-05
  lr_head: 0.0001
  type: full
  warmup: 0.05
  weight_decay: 0.01
log_every: 20
max_length: 128
model: sbert
num_epochs: 50
num_workers: 4
seed: 42
visualize: false
