accum_steps: 16
batch_size: 32
checkpoint: src/ckpts/sbert_full_ibm
checkpoint_dir: src/ckpts
checkpoint_every: null
class_weights:
- 1.0
- 9.320656525220176
- 36.84018987341772
config_file: src/configs/sbert_full_ibm.yaml
dataset: ibm
early_stopping:
  min_delta: 0.001
  patience: 5
experiment_name: sbert_full_ibm
ft_setting:
  ftname: full
  lr_backbone: 5.0e-05
  lr_head: 0.0001
  type: full
  warmup: 0.05
  weight_decay: 0.01
log_every: 200
max_length: 128
model: sbert
num_epochs: 50
num_workers: 4
seed: 42
visualize: false
