batch_size: 32
checkpoint_dir: src/ckps/distilbert
checkpoint_every: null
dataset: abstrct
experiment_name: distilbert_head
ft_setting:
  type: head
learning_rate: 0.01
log_every: 20
max_length: 128
model: distilbert
num_epochs: 5
num_workers: 4
resume_checkpoint: null
seed: 42
