batch_size: 32
checkpoint: src/ckpts/sbert_full_mixed
checkpoint_dir: src/ckpts
checkpoint_every: null
config_file: src/configs/mixed/sbert_full_mixed.yaml
dataset: mixed
early_stopping:
  min_delta: 0.002
  patience: 10
experiment_name: sbert_full_mixed
ft_setting:
  ftname: full
  lr_backbone: 1.0e-05
  lr_head: 1.0e-05
  type: full
  warmup: 0.0
  weight_decay: 0.0
log_every: 20
max_length: 128
model: sbert
num_epochs: 50
num_workers: 4
seed: 42
visualize: false
